name: Draft JOSS paper

on:
  push:
    paths:
      - "paper/**"
      - ".github/workflows/draft-pdf.yml"
  pull_request:
    paths:
      - "paper/**"
      - ".github/workflows/draft-pdf.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Compile paper.md to PDF
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          # This should be the path to the paper within the repo.
          paper-path: paper/paper.md

      - name: Upload compiled PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper
          # The draft-paper action creates the PDF next to paper.md.
          path: paper/paper.pdf
